#!/bin/bash

first_num=0
second_num=0

read -p "Enter the first number --> " first_num
read -p "Enter the second number -> " second_num

echo "$first_num + $second_num = $((first_num + second_num))"
echo "$first_num - $second_num = $((first_num - second_num))"
echo "$first_num * $second_num = $((first_num * second_num))"
echo "$first_num / $second_num = $((first_num / second_num))"
echo "$first_num % $second_num = $((first_num % second_num))"
echo "$first_num raised to the power of $second_num = $((first_num ** second_num))"
